language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
    - CODECOV_TOKEN=02acc17d-8043-4416-96f9-d8fcb499a48c
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x ./gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

script:
  - echo "Hello! This is Travis"
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache